### ISSUE TITLE
Example with npm install doesn't work

### ISSUE THREAD

**Issue by Diferno** [Aller-Couleur/handlebars-i18n#34] opened 2022-02-18 08:27 UTC
Hi!

Have been using your module for currency and numbers for a while. Now I need to i18n text and... found that always returns undefined.
Grabbed the example in your code, and also got undefineds where the text should appear. Is it a version related?

This is the output I get when running the example code using the modules installed from `npm` using this versions:
package.json
```
    "handlebars": "^4.7.7",
    "handlebars-i18n": "^1.3.1",
    "i18next": "^21.6.11",
    "intl": "^1.2.5",
```

```
EXAMPLE OUTPUT:
------------------------
undefined
undefined
undefined
undefined
undefined
undefined 
Deutsch 
7,000.00
3
33.333
€9,999.99
¥1,001
DKK12.99
2/18/2022
3/11/2020
3/11/2020
12/20/2012
2/18/22
3/11/2020
3/11/2020
3/11/2020
3/11/2020
```

This is the output running the same example but requiring the [handlebars-i18n.js that is in your dist](https://github.com/Aller-Couleur/handlebars-i18n/tree/master/dist) folder of the example.

```

EXAMPLE OUTPUT:
------------------------
Was ist gut?
handlebars-i18n ist gut.
1 Gegenstand
7 Gegenstand
Was ist gut?
Die ausgewählte Sprache ist: de
Deutsch 
7.000,00
3
33,333
9.999,99 €
1.001 ¥
12,99 DKK
18.2.2022, 9:33
11.3.2020, 3:24
11.3.2020, 11:35
20.12.2012, 3:00
18.02.22
11.3.2020, 3:24
2020
11.3.2020
3:24:00
```

**Comment by fwalzel** [comment] 2022-02-19 08:50
Okay, here it comes. Since  npm  version >= 7 peer Depenedencies are installed differently.

If you use npm >= 7 do:
`$ npm i handlebars-i18n`

For older versions do:
`$ npm i handlebars-i18n handlebars@4.7.6 i18next@20.2.1 intl@1.2.5`

This resolves the issue. I fixed in in the readme.md. 
Thanks for noticing the problem !

**Closed** 2022-03-23 05:57 UTC

**Comment by rubeonline** [comment] 2022-03-30 09:59
Hi i have the same issue. Im using npm 7.10.0 and installed it via `npm i handlebars-i18n`

When im running your example following error appears:

`Error: Cannot find module '../../dist/handlebars-i18n.js'`

My package.json looks like:
`{
  "name": "handlebars-i18n",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "handlebars-i18n": "^1.4.0"
  }
}`

**Comment by fwalzel** [comment] 2022-03-30 10:06
Have you tried installing via `$ npm i handlebars-i18n handlebars@4.7.6 i18next@20.2.1 intl@1.2.5` ?

**Comment by rubeonline** [comment] 2022-03-30 10:10
Yes. Also with npm 7.10.0. Then this appears:

`````

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: handlebars-i18n@1.0.0
npm ERR! Found: handlebars@4.7.6
npm ERR! node_modules/handlebars
npm ERR!   handlebars@"4.7.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer handlebars@"^4.7.7" from handlebars-i18n@1.4.0
npm ERR! node_modules/handlebars-i18n
npm ERR!   handlebars-i18n@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sergejrube/.npm/eresolve-report.txt for a full report.
`````

**Comment by fwalzel** [comment] 2022-03-30 11:09
Okay, I will try to reproduce your error. Gimme some time, please.

**Comment by swap1789** [comment] 2022-11-15 12:48
Is there an update on this - Even I am getting 'undefined' for the text -
I used npm i handlebars-i18n to install the required dependencies and in my js file I have imported them as follows. Please let me know if I am missing something

import 'handlebars';
import i18next from 'i18next';
import HandlebarsI18n from 'handlebars-i18n';

HandlebarsI18n.init();
const initialize = () => {
  i18next.init({
    resources: {
      en: {
        translation: {
          phrase1: 'What is good?',
          phrase2: '{{thing}} is good.',
        },
      },
      de: {
        translation: {
          phrase1: 'Was ist gut?',
          phrase2: '{{thing}} ist gut.',
        },
      },
    },
    lng: 'en',
  });
};

document.addEventListener('DOMContentLoaded', initialize);
